In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Datadir for location of in/out vars
datadir = '/n/home02/pbb/scripts/SelenkayDiversity/data'

# figd = '/n/home02/pbb/scripts/SelenkayDiversity/figs'

# tabled = '/n/home02/pbb/scripts/SelenkayDiversity/tables'

# Adding labels for different data processing runs
# 'initial'
# mango - 2/8/23
label = 'mango'
# note - features were added and renamed in this run!
# Mainly, the grasslayer metrics of cover and percheights were added
# and all feature names with '()' in them were replaced with '_'

# Radius of lidar data inquiry for modelling
radius = 30

# Open up X and Y vars
XY = pd.read_csv(f'{datadir}/in/XY_scaled_{radius}mRadius.csv')

In [14]:
# filter y vars
y = XY[['Abundance', 'Richness',
        'shannonH', 'Evenness',
        'Soil', 'Treatment']]

# group by 
y_g = y.groupby(['Soil', 'Treatment'])

# Save out summary stats
y_g.mean().to_csv('./tables/YSummaryStats_Mean_SoilTreatment.csv')

y_g.std().to_csv('./tables/YSummaryStats_SD_SoilTreatment.csv')

y_g.sum().to_csv('./tables/YSummaryStats_Sum_SoilTreatment.csv')

y_g.describe()

                Abundance                                                  \
                    count   mean        std    min     25%    50%     75%
Soil  Treatment
Black Inside         15.0  181.4  31.050190  146.0  156.50  178.0  187.00
      Outside        10.0  149.6  29.755298  115.0  128.25  145.0  161.25
Red   Inside         15.0  172.6  51.129807  105.0  140.50  164.0  185.00
      Outside        10.0  143.1  16.387326  123.0  134.00  139.0  151.75

                       Richness             ...  shannonH           Evenness  \
                   max    count       mean  ...       75%       max    count
Soil  Treatment                             ...
Black Inside     253.0     15.0  43.866667  ...  3.472969  3.633004     15.0
      Outside    201.0     10.0  38.800000  ...  3.357037  3.663820     10.0
Red   Inside     287.0     15.0  45.333333  ...  3.558424  3.764023     15.0
      Outside    170.0     10.0  39.600000  ...  3.437680  3.514949     10.0

                                                                             \
                     mean       std       min       25%       50%       75%
Soil  Treatment
Black Inside     0.898013  0.033120  0.823042  0.885578  0.909212  0.922356
      Outside    0.899698  0.025642  0.868324  0.874680  0.901358  0.921820
Red   Inside     0.903693  0.023625  0.860276  0.885572  0.910454  0.919603
      Outside    0.929682  0.013792  0.912292  0.916341  0.930915  0.939728


                      max
Soil  Treatment
Black Inside     0.928266
      Outside    0.931837
Red   Inside     0.928900
      Outside    0.951383

[4 rows x 32 columns]

In [11]:

# group by 
y_g = y.groupby(['Soil'])

# Save out summary stats
y_g.mean().to_csv('./tables/YSummaryStats_Mean_Soil.csv')

y_g.std().to_csv('./tables/YSummaryStats_SD_Soil.csv')

y_g.sum().to_csv('./tables/YSummaryStats_Sum_Soil.csv')

y_g.describe()

In [12]:

# group by 
y_g = y.groupby(['Treatment'])

# Save out summary stats
y_g.mean().to_csv('./tables/YSummaryStats_Mean_Treatment.csv')

y_g.std().to_csv('./tables/YSummaryStats_SD_Treatment.csv')

y_g.sum().to_csv('./tables/YSummaryStats_Sum_Treatment.csv')

In [13]:
y_g.describe()

          Abundance                                                         \
              count    mean        std    min     25%    50%    75%    max
Treatment
Inside         30.0  177.00  41.803316  105.0  152.25  173.0  187.0  287.0
Outside        20.0  146.35  23.615951  115.0  130.75  144.0  156.0  201.0

          Richness        ...  shannonH           Evenness            \
             count  mean  ...       75%       max    count      mean
Treatment                 ...
Inside        30.0  44.6  ...  3.527693  3.764023     30.0  0.900853
Outside       20.0  39.2  ...  3.418560  3.663820     20.0  0.914690


                std       min       25%       50%       75%       max
Treatment
Inside     0.028414  0.823042  0.881272  0.909898  0.921514  0.928900
Outside    0.025262  0.868324  0.906591  0.920642  0.932637  0.951383

[2 rows x 32 columns]