In [34]:
import pandas as pd
import pygam
import matplotlib.pyplot as plt
import numpy as np

# Open outputs from BirdSurveyCleaning.ipynb on Google drive (peter.brehm.boucher folder)
SpotSppDF = pd.read_csv('./data/in/SelenkayBirds_SpotSppDF.csv')
SpotSummaryStats = pd.read_csv('./data/in/DFBirds_SummaryStatsbySpot.csv')

In [36]:
SpotSppDF.head()

,Unnamed: 0,francolin; crested,starling; superb,morning-thrush; spotted,northern white crowned shrike,dove; ring-necked,chanting-goshawk; eastern,bushshrike; rosy-patched,bulbul; common,boubou; slate-colored,...,cisticola; desert,african paradise flycatcher,eastern pale chanting goshawk,parrot; red-bellied,hamerkop,swallow; lesser striped,swallow; red-rumped,bustard; kori,eastern violet backed sunbird,Abundance
0,0,11.0,10.0,2.0,1.0,15.0,1.0,1.0,1.0,6.0,...,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,588.0
1,1,1.0,6.0,1.0,25.0,11.0,2.0,27.0,2.0,7.0,...,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,797.0
2,2,5.0,4.0,9.0,4.0,17.0,9.0,19.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,832.0
3,3,3.0,2.0,6.0,2.0,7.0,2.0,21.0,4.0,6.0,...,0.0,2.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,749.0
4,4,6.0,10.0,2.0,10.0,3.0,8.0,16.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0,805.0

In [35]:
# Add an abundance col (literally, number of raw counts)
# Note- dropping unnamed col for the calculation
# but keeping it to join with Summary stats df 
SpotSppDF['Abundance'] = SpotSppDF.drop('Unnamed: 0', axis=1).sum(axis=1)

In [37]:
SpotSppDF.Abundance.head()

0    588.0
1    797.0
2    832.0
3    749.0
4    805.0
Name: Abundance, dtype: float64

In [9]:
SpotSummaryStats.head()

   Unnamed: 0 Spot  Shannon H  Richness  Evenness
0           0   1A   4.137774       111  0.878596
1           1   1B   4.126547       113  0.872902
2           2   1C   4.005563       113  0.847310
3           3   1D   4.125817       112  0.874392
4           4   1E   3.922487       109  0.836111

In [42]:
# Add the dfs together
SpotSummaryStats_final = SpotSummaryStats.merge(SpotSppDF[['Unnamed: 0', 'Abundance']])
SpotSummaryStats_final.drop('Unnamed: 0', axis=1, inplace=True)
SpotSummaryStats_final.head()

In [46]:
SpotSummaryStats_final.to_csv('./data/out/SpotSummaryStats_Birds_final.csv', index=False, header=True)

In [51]:
# Also, clean and export a version of SpotSppDF
# Add in Spots
SpotSppDF_final = SpotSppDF.merge(SpotSummaryStats[['Unnamed: 0', 'Spot']])
SpotSppDF_final.drop(['Unnamed: 0', 'Abundance'], axis=1, inplace=True)
SpotSppDF_final.set_index('Spot', inplace=True)
SpotSppDF_final.head()

,francolin; crested,starling; superb,morning-thrush; spotted,northern white crowned shrike,dove; ring-necked,chanting-goshawk; eastern,bushshrike; rosy-patched,bulbul; common,boubou; slate-colored,northern pied babblers,...,eagle; martial,cisticola; desert,african paradise flycatcher,eastern pale chanting goshawk,parrot; red-bellied,hamerkop,swallow; lesser striped,swallow; red-rumped,bustard; kori,eastern violet backed sunbird
Spot,,,,,,,,,,,,,,,,,,,,,
1A,11.0,10.0,2.0,1.0,15.0,1.0,1.0,1.0,6.0,21.0,...,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0
1B,1.0,6.0,1.0,25.0,11.0,2.0,27.0,2.0,7.0,8.0,...,0.0,2.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
1C,5.0,4.0,9.0,4.0,17.0,9.0,19.0,1.0,1.0,10.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1D,3.0,2.0,6.0,2.0,7.0,2.0,21.0,4.0,6.0,10.0,...,0.0,0.0,2.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0
1E,6.0,10.0,2.0,10.0,3.0,8.0,16.0,2.0,1.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,1.0

In [52]:
# Export
SpotSummaryStats_final.to_csv('./data/out/SpotSppDF_Birds_final.csv',
                              index=True, header=True)